name: Docker Build

on:
  workflow_call:
    inputs:
      BUILD_DIR:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      TAG:
        required: true
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          cd ./${{ inputs.BUILD_DIR }} && \
          docker buildx build \
            --target prod \
            --push \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            -t ${{ vars.REGISTRY }}/${{ inputs.IMAGE_NAME }}:${{ inputs.TAG }} .
