# build-and-deploy.yml

name: Build and Push Frontend

on:
  push:
    branches:
      - develop

jobs:
  build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    with:
      BUILD_DIR: frontend
      IMAGE_NAME: carservicetracker
      TAG: fe-latest-develop
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  build-backend:
    uses: ./.github/workflows/build-backend.yml
    with:
      BUILD_DIR: backend
      IMAGE_NAME: carservicetracker
      TAG: be-latest-develop
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  deploy:
    runs-on: [self-hosted]
    needs: [build-frontend, build-backend]
    environment: staging
    steps:
      - name: Deploy Docker Compose
        run: |
          cd ${{ vars.DEPLOY_DIR }}
          docker-compose pull
          docker-compose up -d
