name: Build and Push Docker Image

on:
  push:
    branches:
      - develop
#    paths:
#      - frontend/**

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      BUILD_DIR: frontend
      IMAGE_NAME: carservicetracker
      TAG: fe-latest-develop
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}