name: Build and Push Docker Image

on:
  push:
    branches:
      - develop
#    paths:
#      - frontend/**

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      IMAGE_NAME: frontend
      TAG: latest-develop
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}