# docker-publish-frontend.yml

name: Build and Push Docker Image

on:
  push:
    branches:
      - develop
#    paths:
#      - backend/**

jobs:
  build-backend:
    uses: ./.github/workflows/build-backend.yml
    with:
      BUILD_DIR: backend
      IMAGE_NAME: carservicetracker
      TAG: be-latest-develop
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-backend:
    runs-on: [self-hosted]
    needs: build
    environment: staging
    steps:
      - name: Deploy Docker Compose
        run: |
          cd ${{ vars.DEPLOY_DIR }}
          docker-compose pull
          docker-compose up -d

  build-frontend:
    uses: ./.github/workflows/build-fontend.yml
    with:
      BUILD_DIR: frontend
      IMAGE_NAME: carservicetracker
      TAG: fe-latest-develop
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-frontend:
    runs-on: [self-hosted]
    needs: build
    environment: staging
    steps:
      - name: Deploy Docker Compose
        run: |
          cd ${{ vars.DEPLOY_DIR }}
          docker-compose pull
          docker-compose up -d